# Generated by Django 3.0.3 on 2020-02-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='descrition',
            new_name='description',
        ),
    ]
